development:
  adapter:    mysql2
  database:   bydloboard_dev
  username:   YOURNAME
  pool:       5
  timeout:    2000


production:
  adapter:    mysql2
  database:   bydloboard_prod
  username:   YOURNAME
  pool:       5
  timeout:    2000


test:
  adapter:    mysql2
  database:   bydloboard_test
  pool:       5
  timeout:    2000